import { pgTable, uuid, text, numeric, integer, boolean, jsonb, timestamp, index, type AnyPgColumn } from 'drizzle-orm/pg-core';
import { campaigns } from './campaigns';

export const contentPipeline = pgTable('content_pipeline', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  contentId: text('content_id').unique(),
  status: text('status').notNull().default('Potential Idea'),
  pillar: text('pillar'),
  funnelStage: text('funnel_stage'),
  tone: text('tone'),
  platforms: text('platforms').array(),
  format: text('format').array(),
  isEvergreen: boolean('is_evergreen'),
  actionDate: timestamp('action_date', { withTimezone: true }),
  publishDate: timestamp('publish_date', { withTimezone: true }),
  parentContentId: uuid('parent_content_id').references((): AnyPgColumn => contentPipeline.id),
  childContent: uuid('child_content').array(),
  campaignId: uuid('campaign_id').references(() => campaigns.id),
  projects: uuid('projects').array(),
  topicHook: text('topic_hook'),
  contentBody: text('content_body'),
  liveUrl: text('live_url'),
  mediaAssets: jsonb('media_assets'),
  reach: integer('reach'),
  engagement: integer('engagement'),
  clicks: integer('clicks'),
  engagementRate: numeric('engagement_rate', { precision: 5, scale: 4 }),
  content: jsonb('content'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_content_pipeline_status').on(table.status),
  index('idx_content_pipeline_pillar').on(table.pillar),
  index('idx_content_pipeline_funnel_stage').on(table.funnelStage),
  index('idx_content_pipeline_publish_date').on(table.publishDate),
  index('idx_content_pipeline_parent_content_id').on(table.parentContentId),
  index('idx_content_pipeline_campaign_id').on(table.campaignId),
  index('idx_content_pipeline_platforms').on(table.platforms),
  index('idx_content_pipeline_format').on(table.format),
  index('idx_content_pipeline_child_content').on(table.childContent),
  index('idx_content_pipeline_projects').on(table.projects),
]);
