import { pgTable, uuid, text, integer, numeric, timestamp, index, jsonb } from 'drizzle-orm/pg-core';

export const campaigns = pgTable('campaigns', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  campaignId: text('campaign_id').unique(),
  status: text('status'),
  startDate: timestamp('start_date', { withTimezone: true }),
  endDate: timestamp('end_date', { withTimezone: true }),
  durationDays: integer('duration_days'),
  platforms: text('platforms').array(),
  contentTypes: text('content_types').array(),
  automationWorkflows: text('automation_workflows').array(),
  contentFrequency: text('content_frequency'),
  theme: text('theme'),
  summary: text('summary'),
  demographics: text('demographics'),
  psychographics: text('psychographics'),
  seoKeywords: text('seo_keywords'),
  contentWaterfall: text('content_waterfall'),
  targetReach: integer('target_reach'),
  actualReach: integer('actual_reach'),
  engagementRate: numeric('engagement_rate', { precision: 5, scale: 4 }),
  conversionRate: numeric('conversion_rate', { precision: 5, scale: 4 }),
  viralScore: integer('viral_score'),
  budgetAllocated: numeric('budget_allocated', { precision: 12, scale: 2 }),
  projects: uuid('projects').array(),
  contentPipeline: uuid('content_pipeline').array(),
  content: jsonb('content'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_campaigns_status').on(table.status),
  index('idx_campaigns_start_date').on(table.startDate),
  index('idx_campaigns_end_date').on(table.endDate),
  index('idx_campaigns_content_frequency').on(table.contentFrequency),
  index('idx_campaigns_platforms').on(table.platforms),
  index('idx_campaigns_content_types').on(table.contentTypes),
  index('idx_campaigns_automation_workflows').on(table.automationWorkflows),
  index('idx_campaigns_projects').on(table.projects),
  index('idx_campaigns_content_pipeline').on(table.contentPipeline),
]);
