import { pgTable, uuid, text, integer, numeric, timestamp, index } from 'drizzle-orm/pg-core';
import { quarters } from './quarters';

export const months = pgTable('months', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  quartersId: uuid('quarters_id').references(() => quarters.id),
  days: uuid('days').array(),
  financialLog: uuid('financial_log').array(),
  quarterlyGoals: uuid('quarterly_goals').array(),
  year: integer('year'),
  monthNumber: integer('month_number'),
  monthName: text('month_name'),
  monthRange: text('month_range'),
  monthStart: timestamp('month_start', { withTimezone: true }),
  monthEnd: timestamp('month_end', { withTimezone: true }),
  monthJson: text('month_json'),
  status: text('status'),
  totalIncome: numeric('total_income', { precision: 12, scale: 2 }),
  totalExpenses: numeric('total_expenses', { precision: 12, scale: 2 }),
  netCashflow: numeric('net_cashflow', { precision: 12, scale: 2 }),
  categorySummary: text('category_summary'),
  endingNetWorth: numeric('ending_net_worth', { precision: 14, scale: 2 }),
  netWorthChange: numeric('net_worth_change', { precision: 14, scale: 2 }),
  accountsInvolved: text('accounts_involved').array(),
  projectsActive: text('projects_active'),
  cashflowNarrative: text('cashflow_narrative'),
  capitalAllocationInsight: text('capital_allocation_insight'),
  accountsSnapshot: text('accounts_snapshot'),
  keyLearnings: text('key_learnings'),
  significantEvents: text('significant_events'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_months_status').on(table.status),
  index('idx_months_quarters_id').on(table.quartersId),
  index('idx_months_year').on(table.year),
  index('idx_months_month_number').on(table.monthNumber),
  index('idx_months_month_start').on(table.monthStart),
  index('idx_months_month_end').on(table.monthEnd),
  index('idx_months_days').on(table.days),
  index('idx_months_financial_log').on(table.financialLog),
  index('idx_months_quarterly_goals').on(table.quarterlyGoals),
  index('idx_months_accounts_involved').on(table.accountsInvolved),
]);
