import { pgTable, uuid, text, integer, timestamp, index } from 'drizzle-orm/pg-core';

export const people = pgTable('people', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  firstName: text('first_name'),
  customName: text('custom_name'),
  summary: text('summary'),
  strategicContext: text('strategic_context'),
  engagementBlueprint: text('engagement_blueprint'),
  professionalDomain: text('professional_domain'),
  originContext: text('origin_context'),
  keyPersonalIntel: text('key_personal_intel'),
  email: text('email'),
  connectionFrequencyDays: integer('connection_frequency_days'),
  lastConnectedDate: timestamp('last_connected_date', { withTimezone: true }),
  reconnectBy: text('reconnect_by'),
  networkingProfile: text('networking_profile'),
  relationshipStatus: text('relationship_status'),
  valueExchangeBalance: text('value_exchange_balance'),
  coreShadow: text('core_shadow'),
  developmentalAltitude: text('developmental_altitude'),
  aspirationalDrive: text('aspirational_drive'),
  temporalFocus: text('temporal_focus'),
  primaryCenterOfIntelligence: text('primary_center_of_intelligence'),
  dominantPowerStrategy: text('dominant_power_strategy'),
  city: text('city'),
  primaryConflictStyle: text('primary_conflict_style'),
  timezone: text('timezone'),
  desiredTrajectory: text('desired_trajectory'),
  stabilityProfile: text('stability_profile'),
  lastInteractionSentiment: text('last_interaction_sentiment'),
  explanatoryStyle: text('explanatory_style'),
  influenceToolkit: text('influence_toolkit').array(),
  communityId: uuid('community_id'),
  stories: uuid('stories').array(),
  projects: uuid('projects').array(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_people_networking_profile').on(table.networkingProfile),
  index('idx_people_relationship_status').on(table.relationshipStatus),
  index('idx_people_value_exchange_balance').on(table.valueExchangeBalance),
  index('idx_people_desired_trajectory').on(table.desiredTrajectory),
  index('idx_people_city').on(table.city),
  index('idx_people_timezone').on(table.timezone),
  index('idx_people_last_connected_date').on(table.lastConnectedDate),
  index('idx_people_community_id').on(table.communityId),
  index('idx_people_stories').on(table.stories),
  index('idx_people_projects').on(table.projects),
  index('idx_people_influence_toolkit').on(table.influenceToolkit),
  index('idx_people_dominant_power_strategy').on(table.dominantPowerStrategy),
  index('idx_people_primary_conflict_style').on(table.primaryConflictStyle),
  index('idx_people_explanatory_style').on(table.explanatoryStyle),
]);
