import { pgTable, uuid, text, numeric, timestamp, index, jsonb } from 'drizzle-orm/pg-core';
import { quarterlyGoals } from './quarterly_goals';

export const projects = pgTable('projects', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  projectId: text('project_id').unique(),
  status: text('status').notNull().default('On Hold'),
  phase: text('phase'),
  priority: text('priority'),
  team: text('team').array(),
  projectStart: timestamp('project_start', { withTimezone: true }),
  deadline: timestamp('deadline', { withTimezone: true }),
  reviewDate: timestamp('review_date', { withTimezone: true }),
  budgetAllocated: numeric('budget_allocated', { precision: 12, scale: 2 }),
  budgetSpent: numeric('budget_spent', { precision: 12, scale: 2 }),
  requiredBudget: numeric('required_budget', { precision: 12, scale: 2 }),
  projectedRevenue: numeric('projected_revenue', { precision: 12, scale: 2 }),
  projectSummary: text('project_summary'),
  justification: text('justification'),
  kpi: text('kpi'),
  kpiStatus: text('kpi_status'),
  strategy: text('strategy'),
  quarterlyGoalId: uuid('quarterly_goal_id').references(() => quarterlyGoals.id),
  tasks: uuid('tasks').array(),
  dependsOn: uuid('depends_on').array(),
  dependents: uuid('dependents').array(),
  people: uuid('people').array(),
  campaigns: uuid('campaigns').array(),
  activityLog: uuid('activity_log').array(),
  financialLog: uuid('financial_log').array(),
  systemicJournal: uuid('systemic_journal').array(),
  documents: uuid('documents').array(),
  notes: uuid('notes').array(),
  directivesRisks: uuid('directives_risks').array(),
  opportunities: uuid('opportunities').array(),
  health: text('health'),
  monitor: text('monitor'),
  progress: numeric('progress', { precision: 5, scale: 2 }),
  projectJson: text('project_json'),
  projectProgress: text('project_progress'),
  durationDays: text('duration_days'),
  costToDate: numeric('cost_to_date', { precision: 12, scale: 2 }),
  lastEditedAt: timestamp('last_edited_at', { withTimezone: true }),
  content: jsonb('content'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_projects_status').on(table.status),
  index('idx_projects_phase').on(table.phase),
  index('idx_projects_priority').on(table.priority),
  index('idx_projects_deadline').on(table.deadline),
  index('idx_projects_quarterly_goal_id').on(table.quarterlyGoalId),
  index('idx_projects_team').on(table.team),
  index('idx_projects_tasks').on(table.tasks),
  index('idx_projects_depends_on').on(table.dependsOn),
  index('idx_projects_dependents').on(table.dependents),
  index('idx_projects_people').on(table.people),
  index('idx_projects_campaigns').on(table.campaigns),
  index('idx_projects_activity_log').on(table.activityLog),
  index('idx_projects_financial_log').on(table.financialLog),
  index('idx_projects_systemic_journal').on(table.systemicJournal),
  index('idx_projects_documents').on(table.documents),
  index('idx_projects_notes').on(table.notes),
  index('idx_projects_directives_risks').on(table.directivesRisks),
  index('idx_projects_opportunities').on(table.opportunities),
]);
