import { pgTable, uuid, text, numeric, boolean, timestamp, index, jsonb } from 'drizzle-orm/pg-core';
import { annualGoals } from './annual_goals';

export const quarterlyGoals = pgTable('quarterly_goals', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  goalId: text('goal_id').unique(),
  annualGoalId: uuid('annual_goal_id').references(() => annualGoals.id),
  quarters: uuid('quarters').array(),
  projects: uuid('projects').array(),
  directivesRiskLog: uuid('directives_risk_log').array(),
  opportunitiesStrengths: uuid('opportunities_strengths').array(),
  status: text('status').notNull().default('Planning'),
  isCurrentGoal: boolean('is_current_goal'),
  goalProgress: text('goal_progress'),
  progress: numeric('progress', { precision: 5, scale: 2 }),
  health: text('health'),
  monitor: text('monitor'),
  plannedRange: text('planned_range'),
  quarterlyGoalJson: text('quarterly_goal_json'),
  keyResult1: text('key_result_1'),
  keyResult2: text('key_result_2'),
  keyResult3: text('key_result_3'),
  keyLearning: text('key_learning'),
  content: jsonb('content'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_quarterly_goals_status').on(table.status),
  index('idx_quarterly_goals_annual_goal_id').on(table.annualGoalId),
  index('idx_quarterly_goals_goal_id').on(table.goalId),
  index('idx_quarterly_goals_progress').on(table.progress),
  index('idx_quarterly_goals_quarters').on(table.quarters),
  index('idx_quarterly_goals_projects').on(table.projects),
  index('idx_quarterly_goals_directives_risk_log').on(table.directivesRiskLog),
  index('idx_quarterly_goals_opportunities_strengths').on(table.opportunitiesStrengths),
  index('idx_quarterly_goals_is_current_goal').on(table.isCurrentGoal),
]);
