import { pgTable, uuid, text, integer, numeric, timestamp, index } from 'drizzle-orm/pg-core';

export const weeks = pgTable('weeks', {
  id: uuid('id').primaryKey().defaultRandom(),
  dataSourceId: uuid('data_source_id').notNull(),
  name: text('name').notNull(),
  days: uuid('days').array(),
  tasks: uuid('tasks').array(),
  financialLog: uuid('financial_log').array(),
  year: integer('year'),
  weekNumber: integer('week_number'),
  weekName: text('week_name'),
  weekRange: text('week_range'),
  weekStart: timestamp('week_start', { withTimezone: true }),
  weekEnd: timestamp('week_end', { withTimezone: true }),
  weekJson: text('week_json'),
  status: text('status'),
  tasksProgress: text('tasks_progress'),
  activityBreakdown: text('activity_breakdown'),
  totalIncome: numeric('total_income', { precision: 12, scale: 2 }),
  totalExpenses: numeric('total_expenses', { precision: 12, scale: 2 }),
  netCashflow: numeric('net_cashflow', { precision: 12, scale: 2 }),
  categorySummary: text('category_summary'),
  keyLearnings: text('key_learnings'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_weeks_status').on(table.status),
  index('idx_weeks_year').on(table.year),
  index('idx_weeks_week_number').on(table.weekNumber),
  index('idx_weeks_week_start').on(table.weekStart),
  index('idx_weeks_week_end').on(table.weekEnd),
  index('idx_weeks_days').on(table.days),
  index('idx_weeks_tasks').on(table.tasks),
  index('idx_weeks_financial_log').on(table.financialLog),
]);
